angular
  .module('vitals',
    [
      'application',
      'bahmni.common.appFramework',
      'bahmni.common.config',
      'bahmni.common.domain',
      'bahmni.common.i18n',
      'bahmni.common.uicontrols.programmanagment',
      'bahmni.common.uiHelper',
      'common.patient',
      'frapontillo.bootstrap-switch',
      'LocalStorageModule',
      'ngCookies',
      'ngDialog',
      'ngMessages',
      'ngRoute',
      'pascalprecht.translate',
      'patient.details',
      'poc.common.clinicalservices',
      'smart-table',
      'ui.checkbox',
      'ui.router'
    ]
  );
